[package]
name = "use-type-unit"
description = "Primitive typographic unit helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-type-unit"
keywords = ["typography", "unit", "rem", "em", "pt"]
categories = ["algorithms", "science"]

[lints]
workspace = true