[package]
name = "use-type-rhythm"
description = "Primitive type-rhythm helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-type-rhythm"
keywords = ["typography", "rhythm", "baseline", "layout"]
categories = ["algorithms", "science"]

[lints]
workspace = true
