[package]
name = "use-typography-measure"
description = "Primitive readable-measure helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-typography-measure"
keywords = ["typography", "measure", "readability", "text"]
categories = ["algorithms", "science"]

[lib]
name = "use_measure"

[lints]
workspace = true